### ISSUE TITLE
Update folder name to install the plugin

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#251] opened 2018-01-10 20:41 UTC
### Expected behaviour

Update to flyvemdm the setup information to install older versions of Flyve MDM plugin

### Actual behaviour

The version 1.1.0 requires that the uncompressed folder to be named storkmdm in order to be installed

### Environment Details

- HTTP server version:
- GLPi version: 9.1.6
- Flyve MDM version: 1.1.0
- FusionInventory version: 9.1 + 1.0
- Mosquitto version:
- Mosquitto's auth plugin  version:

### Steps to reproduce the behaviour

1. Uncompress the Flyve MDM version 1.1.0 in the GLPI plugins directory
2. Rename it to flyvemdm
3. Go to Setup > Plugins on GLPI (Only appears fusioninventory plugin)
4. Rename flyvemdm to storkmdm
5. Go to Setup > Plugins on GLPI (Now both plugins appear)

**Comment by DIOHz0r** [comment] 2018-01-24 13:39
@btry  this change was a braking change, so I think this issue is more related to documentation. Are you ok with this or with another topic?

**Comment by btry** [comment] 2018-01-24 13:48
Well, this is a bit aggressive to say this is a breaking change. 

Actually I think the problem is that there is not yet any release of the plugin with its current name.

I think we could add one or two lines to warn about this issue in the documentation. Once the release is done, I think we should drop support for the old storkmdm versions, because 1 year elapsed already, and the product greatly evolved.

we could plan 2 releases later to remove the lines I suggested to add above.

**Comment by Naylin15** [comment] 2018-01-30 17:42
Hi, 

I already added a line about the change of name of the plugin in the installation article

![captura de pantalla 2018-01-30 a la s 1 35 06 p m](https://user-images.githubusercontent.com/30867977/35581816-5fb4b2e0-05c3-11e8-9166-4f604d9a2a02.png)

**Comment by btry** [comment] 2018-01-31 08:41
Hi 

If the change is merged, please close this issue.

**Closed** 2018-01-31 12:41 UTC
Labels: documentation
