### ISSUE TITLE
PHP Error Undefined offset ... task.class.php 

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#800] opened 2018-11-20 19:18 UTC
**Describe the bug**

![screencapture-dev-flyve-org-glpi-plugins-flyvemdm-front-fleet-form-php-2018-11-20-15_09_39](https://user-images.githubusercontent.com/4085091/48796920-3e2c1400-ecd7-11e8-940d-ff5f1c42bab0.png)

**To Reproduce**
1. Go to GLPI dev environment
2. Click on Fleets
3. Go to Fleet FlyveDevMyc
4. Click task
5. See the error

**Comment by btry** [comment] 2018-11-21 07:48
Hi

From the source code I see the error seems caused by tasks linked to policies which don't exist. I think this is caused by removal of some policies from the version 2.0.0 because the mdm agent does not support them yet. The content of the fleet and its history shows this is a fleet done for tests; One of us linked policies, then we deleted some and this fleet was not updated. All of this happened in november 2017.

This is a special case due to our development activities and will not happen in a normal use, I think we can close without any risk.

@DIOHz0r : I let you tell your opinion. 
@ajsb85 : look at the history of this fleet. You did a lot of changes, you might give some useful information if you were the creator of this fleet.

**Comment by DIOHz0r** [comment] 2018-12-05 17:51
I agree, let's close this issue and clean up the dev database to avoid a misunderstanding

**Closed by DIOHz0r** 2018-12-05 17:51 UTC
