### ISSUE TITLE
PHP-error.log not empty because one XML import notice from FusionInventory plugin

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/glpi-plugin#236] opened 2017-12-20 13:02 UTC
### Expected behaviour
Agent integration test asserts an empty log on enrollment  

### Actual behaviour
An php notice is writting during the tests of the agent enrollment making the rest of the test falling. the issue is related to a missing index importing the XML with FI fusioninventory/fusioninventory-for-glpi#2388

### Environment Details

- GLPi version: 9.2
- Flyve MDM version: 2.0-dev
- FusionInventory version: 9.2

### Steps to reproduce the behaviour

1. Set-up the test enviroment with the .travis.yml "before_script" commands
2. run vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install -ncc
3. run vendor/bin/atoum -ft -bf tests/bootstrap.php --ncc -f tests/suite-integration/PluginFlyvemdmAgent.php -t testEnrollAgent

### Screenshots, backtraces or logs

php-errors.log
```
*** PHP Notice(8): Undefined index: name
  Backtrace :
  ...nventory\inc\inventorycomputerlib.class.php:187 
  ...ry\inc\inventorycomputerinventory.class.php:573 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1461                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:234 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\flyvemdm\inc\agent.class.php:1231          PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\flyvemdm\inc\agent.class.php:455           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc\commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  ...s\suite-integration\PluginFlyvemdmAgent.php:871 CommonDBTM->add()
  ...\suite-integration\PluginFlyvemdmAgent.php:1000 tests\units\PluginFlyvemdmAgent->enrollFromInvitation()
  ...s\suite-integration\PluginFlyvemdmAgent.php:203 tests\units\PluginFlyvemdmAgent->agentFromInvitation()
  ...yvemdm\vendor\atoum\atoum\classes\test.php:1270 tests\units\PluginFlyvemdmAgent->testEnrollAgent()
  ...\atoum\atoum\classes\test\engines\inline.php:43 mageekguy\atoum\test->runTestMethod()
  ...yvemdm\vendor\atoum\atoum\classes\test.php:1807 mageekguy\atoum\test\engines\inline->run()
  ...yvemdm\vendor\atoum\atoum\classes\test.php:1716 mageekguy\atoum\test->runEngine()
  ...yvemdm\vendor\atoum\atoum\classes\test.php:1384 mageekguy\atoum\test->runEngines()
  ...vemdm\vendor\atoum\atoum\classes\runner.php:597 mageekguy\atoum\test->run()
  ...dor\atoum\atoum\classes\scripts\runner.php:1250 mageekguy\atoum\runner->run()
  ...vemdm\vendor\atoum\atoum\classes\script.php:285 mageekguy\atoum\scripts\runner->doRun()
  ...\atoum\atoum\classes\script\configurable.php:80 mageekguy\atoum\script->run()
  ...ndor\atoum\atoum\classes\scripts\runner.php:214 mageekguy\atoum\script\configurable->run()
  ...ndor\atoum\atoum\classes\scripts\runner.php:699 mageekguy\atoum\scripts\runner->run()
  :                                                  mageekguy\atoum\scripts\runner::mageekguy\atoum\scripts\{closure}()
```

**Comment by btry** [comment] 2017-12-29 08:15
I think the issue is fixed with #233

**Comment by DIOHz0r** [comment] 2017-12-29 14:04
What does this have to do with the issue about package upload? or do you mean #165 ???

**Comment by btry** [comment] 2017-12-29 14:58
well I worked so hard to solve these few issues in the branch I can't tell you anymore. But I had this backtrace and I worked to solve it.

**Closed** 2018-01-03 20:37 UTC
