### ISSUE TITLE
Reset password policy require string on Android

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#297] opened 2018-02-01 22:34 UTC
#### Observed Results:
The reset password policy display a list with boolean value (yes/no) but could be a string with the new password

<img width="942" alt="captura de pantalla 2018-02-01 a la s 6 27 40 p m" src="https://user-images.githubusercontent.com/4085091/35706867-cd9f4ef8-077d-11e8-9d53-d2ba4f216b60.png">
  
#### Expected behavior:

The reset password policy on Android requires a message with the string of the new password of the user

the actual message is like this:
`{"resetPassword":"true","taskId":188}`

This is the proposal message for Android:
`{"resetPassword":"new_password","taskId":188}`

**Comment by btry** [comment] 2018-02-02 09:26
Hi

This policy is problematic. Currently a policy applies on a fleet. Then if we change the policy to be a string policy, we will set a unique password to all devices on a single fleet. 

- We need first to implement application of policies on a single device
- next we implement a system to allow some policies to be applied only on a single device, not a fleet.

**Comment by btry** [comment] 2018-02-02 09:27
Also, changing this policy to a string type is very easy. This is a single line of code, and additionally check the upgrade system can handle such case.

**Comment by DIOHz0r** [comment] 2018-02-02 14:06
Maybe we can add a change to the "add policy form" on the fleets to hidden policies that are per device only.

**Comment by btry** [comment] 2018-02-02 14:49
We are not yet at this point as we can only apply a policy to a fleet :D 

This is a big evolution of the backend, and I need study if my idea of implementation us achievable. It depends on the GLPI framework IMO

**Comment by rafaelje** [comment] 2018-02-02 15:14
Review if we can change this policy to a command like Ping or Inventory

**Comment by btry** [comment] 2018-02-02 16:37
If we change it to a command, we will not be able to get feedback from the agent. For a password, I think this is important.

I would be in favor of removing this policy until we implement the features I mentioned above.

**Comment by btry** [comment] 2018-02-02 16:38
If I remember correctly, the reset password was designed to be only a bool, because the agent will prompt the user for a new password.

We might do something similar to the unlock feature.

**Comment by rafaelje** [comment] 2018-02-02 17:18
but if the device is locked and he forgot the password, we cannot prompt this message to the user

**Comment by btry** [comment] 2018-02-05 06:49
Convrrting the policy to a command may be dangerous because commands are not designed to send a feedback.

As too many password attempts may lead to a wipe, the user and the admin both need to know if the reset succeeded. I think we must keep this as a policy. 

We need to enhance the back end to show feedbacks (not implemented yet), publish policies to a single device, maybe allow policies to publish to a device only, then make the policy available. For now, we might set a bool to enable or not policies to the admin.

**Comment by btry** [comment] 2018-05-11 09:37
This issue was fixed in this commit 386ceb90e087fc101826617306e1af8c65dd7fc9

Too early because the policies on devices were not merged :/

**Closed by btry** 2018-05-11 09:37 UTC
Labels: bug
