### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#863] opened 2019-01-05 04:14 UTC
PHP Notice: Undefined offset: 23 in /var/www/public/glpi/plugins/flyvemdm/inc/task.class.php at line 679

Reference:
https://dev.flyve.org/glpi/plugins/flyvemdm/front/fleet.form.php?id=58

![image](https://user-images.githubusercontent.com/663460/50720200-ad53a100-10a8-11e9-8c1e-4cad444775a6.png)

**Comment by btry** [comment] 2019-01-10 08:54
No backtrce, no context, item deleted then unable to reproduce and find missing info. closing

**Closed by btry** 2019-01-10 08:54 UTC
Labels: bug
